apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo
spec:
  accessModes:
    -  ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata: 
  name: demo
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: "/mnt"
      name: demo
  volumes:
    - name: demo
      persistentVolumeClaim:
        claimName: demo