apiVersion: extensions/v1beta1
      #deployment / pod / service
kind: Deployment
metadata:
      #name form the deployment / pod / service
  name: nodejs-deployment
      #deployments`s specification:
spec:
      #number of replicas on each pod
  replicas: 1
      #how to update the pods?
  strategy: Recreate
      #Which pods are manageed by this deployment?
  selector:
      #Match labels on the Pods!
    matchLabels:
      app: nodejs
      #POD configuration template nested inside deployment
  template:
    metadata:
      #Set labels on the pod
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: x0r5/nodejs
        ports:                                      
        - containerPort: 3000                       
          name: http                                
        - containerPort: 22                         
          name: ssh                                 
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nodejs-service
# spec:
#   selector:
#     app: nodejs
#   ports:
#   - port: 32000
#     #inside the cluster what port does the service expose? expose the service on the port internally within the cluster, the service becomes visible on this port 
#     #service port:
    
#     #which port do pods selected by this service expose? the port on the pod that the request is sent to
#     #pod's port
#     targetPort: 3000
#     #which port on the node is the service available through? makes the service visible outside the cluster
#     #node's port visible outside
#     nodePort: 32000
#   #make the service externally visible via the node:
#   type: NodePort