apiVersion: extensions/v1beta1   #deployment / pod / service
kind: Deployment
metadata:    #name form the deployment / pod / service
  name: minecraft-deployment
spec:    #deployments`s specification:
  replicas: 1    #number of replicas on each pod
  #strategy: Recreate    #how to update the pods? DO NOT UNCOMMENT
  selector:     #Which pods are manageed by this deployment?
    matchLabels:    #Match labels with the Pods!
      app: minecraft
  template:    #POD configuration template nested inside deployment
    metadata:
      labels:    #Set labels on the pod
        app: minecraft
    spec:
      containers:
      - name: minecraft-container
        image: x0r5/minecraft-2
        ports:                                      
        - containerPort: 25565
---
kind: Service
apiVersion: v1
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
  - protocol: TCP
    targetPort: 25565   #POD`s port, the request is sent to it
    port: 25565    #external IP