apiVersion: extensions/v1beta1   #deployment / pod / service
kind: Deployment
metadata:    #name form the deployment / pod / service
  name: nodejs-deployment
spec:    #deployments`s specification:
  replicas: 3    #number of replicas on each pod
  #strategy: Recreate    #how to update the pods? DO NOT UNCOMMENT
  selector:     #Which pods are manageed by this deployment?
    matchLabels:    #Match labels with the Pods!
      app: nodejs
  template:    #POD configuration template nested inside deployment
    metadata:
      labels:    #Set labels on the pod
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: x0r5/nodejs
        ports:                                      
        - containerPort: 3000                       
          name: http                                
        - containerPort: 22                         
          name: ssh      
---
  kind: Service
  apiVersion: v1
  metadata:
    name: nodejs-service
  spec:
    selector:
      app: nodejs
    ports:
    - protocol: TCP
      targetPort: 3000   #POD`s port, the request is sent to it
      port: 80    #external IP
      name: http
    - protocol: TCP
      targetPort: 22
      port: 22
      name: ssh
    type: LoadBalancer