apiVersion: v1
kind: PesistentVolume
metadata:
  name: mysqlvol
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    -  ReadWriteOnce
  hostPath:
    path: "/mnt/data" #host location