kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-minecraft
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" #does it matter?
  persistentVolumeReclaimPolicy: Recycle
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi