apiVersion: v1
data:
  postgres_password_value: NUhoYnpJR1RsRUtlVWE3UlZkRjUK
  initdb.sql: LS0gVGhpcyBpcyBhIHBvc3RncmVzIGluaXRpYWxpemF0aW9uIHNjcmlwdCBmb3IgdGhlIHBvc3RncmVzIGNvbnRhaW5lci4gDQotLSBXaWxsIGJlIGV4ZWN1dGVkIGR1cmluZyBjb250YWluZXIgaW5pdGlhbGl6YXRpb24gKCQ+IHBzcWwgcG9zdGdyZXMgLWYgaW5pdGRiLnNxbCkNCkNSRUFURSBST0xFIGFkc3VzZXIgV0lUSCBMT0dJTiBQQVNTV09SRCAnaW5pdGlhbCcgSU5IRVJJVCBDUkVBVEVEQjsNCkNSRUFURSBEQVRBQkFTRSBhZHMgV0lUSCBFTkNPRElORyAnVU5JQ09ERScgTENfQ09MTEFURSAnQycgTENfQ1RZUEUgJ0MnIFRFTVBMQVRFIHRlbXBsYXRlMDsNCkdSQU5UIEFMTCBQUklWSUxFR0VTIE9OIERBVEFCQVNFIGFkcyBUTyBhZHN1c2VyOw0KQ1JFQVRFIFNDSEVNQSBhZHMgQVVUSE9SSVpBVElPTiBhZHN1c2VyOw0KLS0gQUxURVIgREFUQUJBU0UgYWRzIFNFVCBzZWFyY2hfcGF0aCBUTyAnYWRzJzsNCkFMVEVSIERBVEFCQVNFIGFkcyBPV05FUiBUTyBhZHN1c2VyOw==
kind: Secret
metadata:
  name: ads-db-secret
  labels:
    component: ads
    module: db
type: Opaque