apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1G
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi